### ISSUE TITLE
WD3 out of date

### ISSUE THREAD

**Issue by ral104** [zooniverse/operationwardiary#63]
Looks like WD3 has not updated for a while.

E.g. 48 Infantry Brigade, 22 Battalion Northumberland Fusiliers is not in the 'complete' list on wd3

Tried going directly to image AWD0003e3p in wd3 from this diary as well, but no luck.

**Comment by eatyourgreens** [comment]
Pinging @astopy who can probably check to see if the WD3 classification data is updating properly.

**Comment by astopy** [comment]
This should be working now.

**Comment by ral104** [comment]
it is - thanks!
